language: node_js
node_js:
  - 10.12.0
install:
  - npm install
  - npm instal --global cross-env
branches:
  only:
    - rachel
    - master
  deploy:
    provider: heroku
    api_key:
      secure:
    app:
      rachel: onesg-frontend-staging
      master: onesg-frontend
      skip_cleanup: 'true'
